### PR TITLE
Incorporation of new hardware encoder module (QDC)

### PR DESCRIPTION
**Pull request by rbobey1989**
Hello Scott, I have been working on your Remora Rt1052-cpp project for a few days, I have been studying how the QDC and XBAR module works, I am attaching some photos of the tests I have done, I have added some commits with detailed descriptions of the files that I have modified, take a look, greetings, everything is for LinuxCNC and Remora
enc_remora_00
enc_remora_01
enc_remora_03

### CODE REVIEW

**Review by scottalford75 — COMMENTED** [review]
With regard to the index pin interrupt. IMO it would be better to have the index pin as a normal input interrupt rather than the encoder interrupt. That way we could use any input and leave the XBAR capable inputs for A and B phases.

**Comment by rbobey1989** [comment]
ok, good approach, I hadn't thought about this or I didn't understand you before on the linuxcnc forum.
Change the Index interruption in the Encoder for a normal pin interruption, next change thanks

**Comment by rbobey1989** [comment]
There is something I was thinking about and that is that with the implementation of the Index interruption through GPIO we do not have the possibility of filtering the Pin Index signal, I remind you that the glitch filter adds delay to the signals so we would have to try a little more thoroughly....

**Comment by rbobey1989** [comment]
although I repeat at the speeds I have tested it works well

**Pull request merged**
