### PR TITLE
Qdc index gpio interrupt

### PR DESCRIPTION
**Pull request by rbobey1989**
Hi Scott, I have created a new branch for the GPIO interrupt implementation for the Index pin, I have tested it and it works fine, take a look and tell me...

It was a little difficult for me to realize that I had to disable interruptions in the configuration file loading process..., I'm still not entirely clear if you can shed some light on this, thank you

### CODE REVIEW

**Review by scottalford75 — COMMENTED** [review]
Cool, I'll be back tomorrow and I've had notice that my encoder for testing has arrived whilst I've been away. 

As we're using a shared interrupt we'll need to test which input has triggered the interrupt and then fire the appropriate qdc handle interrupt. Otherwise multiple encoders will have there index event triggered. A downside to the shared input interrupt unfortunately...

**Comment by rbobey1989** [comment]
haha, I saw your comment and reviewed my code and I see that I had not asked for the pin that requested interruption, I could have sworn I had done that mmmm, well I have implemented the above and I had to make some minor changes to the remora-nv module. h (VARIABLES = 4), I have also set the priority of the interruption for the encoders to 4, regarding the latter I listen to your opinion on the matter, greetings

**Comment by scottalford75** [comment]
Thanks, I'm merging this now for testing. 

I've been scratching my head on the index interrupt. I could be wrong but with the current implementation if we have two index pins on the same shared interrupt, then the vector table will only point to the last registered qdc interrupt.

We'll probably need an intermediate interrupt handler(s) with it's own table so that we can test which input triggered the interrupt and then jump to to index event for that encoder.

**Comment by rbobey1989** [comment]
I have tried with two instances of qdc with index but looking once again at the pins that I used for Index and they are from different vectors, so I would have to try it with two in the same vector, it is not entirely clear to me what can happen so I would have to try, but you may be right, I hope for some conclusion from your tests, greetings

**Comment by scottalford75** [comment]
Hi, I've just hooked up the encoder and it's working! Looks to increment
count on every A and B transition so my 500 PPR encoder is producing 2000
counts per revolution. Does this sound right? I need to print up a mount to
attach it to a stepper motor to start testing the index homing.

I've got some ideas for a portInterrupt class which would be useful for any
of the port 3 and port 4 inputs.

**Comment by rbobey1989** [comment]
well, I imagined it would work without problems hehe, although obviously there are still stones in the way but we will have to continue....., I will follow your ideas about the portInterrupt class, first we crawl, then we walk and finally we run, 500 ppr x 4 = 2000 counts, that's ok, pins 17 and 15 are the respective Index entries to read on the LinuxCnC part, I'm glad everything is working

**Comment by rbobey1989** [comment]
Hello Scott, I'm afraid that you are very right about the issue of the two index pins in the same interruption vector, I even lose connection with the EC500 board, I don't know if you have looked at the issue at all, I am going to start looking to solve this from the point I am at now, greetings, wish me luck hehe

**Comment by scottalford75** [comment]
My idea was to have a class similar to the Interrupt class, with 4 ISR
wrappers. The portInterupt class would have 4 vector tables, one for each
combined interrupt. The interrupt owner would register its callback against
the required port and pin vector table. The ISR wrapper would check which
pin triggered the interrupt and then trigger the callback.

**Comment by rbobey1989** [comment]
Hi Scott, I have been working on the Qdc module and I think I have a working version of the last idea we talked about, I have followed your implementation ideas and it looks good, I have done some tests and we no longer have the problem of several pins matching on the same interruption vector, take a look when you can and tell me what you think, greetings

**Pull request merged**
